name: PIN
version: ${project.version}
description: Public PIN plugin.
author: Tractopelle

main: fr.tractopelle.pin.CorePlugin

commands:
  pin:
    description: Main command of the plugin.
  pinadmin:
    description: Main Admin command of the plugin.
